import { Html, html } from 'foldkit/html'

import type { TableOfContentsEntry } from '../main'
import type { Message } from '../message'
import {
  bullets,
  infoCallout,
  inlineCode,
  link,
  pageTitle,
  para,
  tableOfContentsEntryToHeader,
  warningCallout,
} from '../prose'
import {
  apiModuleRouter,
  comingFromTanStackQueryRouter,
  coreCommandsRouter,
  coreModelRouter,
  exampleDetailRouter,
  fieldValidationRouter,
} from '../route'
import * as Snippet from '../snippet'
import { type CopiedSnippets, highlightedCodeBlock } from '../view/codeBlock'
import { comparisonTable } from '../view/table'

const plainCode = (text: string): Html => {
  const h = html<Message>()

  return h.code([h.Class('text-sm')], [text])
}

const overviewHeader: TableOfContentsEntry = {
  level: 'h2',
  id: 'overview',
  text: 'Overview',
}

const sixStatesHeader: TableOfContentsEntry = {
  level: 'h2',
  id: 'the-six-states',
  text: 'The Six States',
}

const staleWhileRevalidateHeader: TableOfContentsEntry = {
  level: 'h2',
  id: 'stale-while-revalidate-and-keep-stale-on-failure',
  text: 'Stale-While-Revalidate and Keep-Stale-on-Failure',
}

const schemaBuilderHeader: TableOfContentsEntry = {
  level: 'h2',
  id: 'the-schema-builder',
  text: 'The Schema Builder',
}

const workingWithTheValueHeader: TableOfContentsEntry = {
  level: 'h2',
  id: 'working-with-the-value',
  text: 'Working With the Value',
}

const revalidatingHeader: TableOfContentsEntry = {
  level: 'h2',
  id: 'revalidating',
  text: 'Revalidating',
}

const settlingAFetchHeader: TableOfContentsEntry = {
  level: 'h2',
  id: 'settling-a-fetch',
  text: 'Settling a Fetch',
}

const combiningSeveralHeader: TableOfContentsEntry = {
  level: 'h2',
  id: 'combining-several',
  text: 'Combining Several',
}

export const tableOfContents: ReadonlyArray<TableOfContentsEntry> = [
  overviewHeader,
  sixStatesHeader,
  staleWhileRevalidateHeader,
  schemaBuilderHeader,
  workingWithTheValueHeader,
  revalidatingHeader,
  settlingAFetchHeader,
  combiningSeveralHeader,
]

export const view = (copiedSnippets: CopiedSnippets): Html => {
  const h = html<Message>()

  return h.div(
    [],
    [
      pageTitle('async-data', 'Async Data'),
      para(
        inlineCode('foldkit/asyncData'),
        ' is a shipped Foldkit module: a plain value type in the spirit of ',
        inlineCode('Option'),
        ' and ',
        inlineCode('Result'),
        ' from Effect, built for data that arrives asynchronously. It provides a value type, not an application pattern. This page introduces the type, the mental model, and the combinators you reach for most. The ',
        link(apiModuleRouter({ moduleSlug: 'async-data' }), 'API Reference'),
        ' has the exhaustive catalog.',
      ),

      tableOfContentsEntryToHeader(overviewHeader),
      para(
        'Server data in a Model is never just data or nothing. Between “we have it” and “we do not” sit “we asked and are waiting”, “the ask failed”, “we have last week’s copy and are refetching”, and “the refetch failed but we kept the copy”. A boolean ',
        inlineCode('isLoading'),
        ' next to a nullable ',
        inlineCode('data'),
        ' field cannot tell those apart, and every screen that renders the field ends up re-deriving the distinction from a tangle of flags.',
      ),
      para(
        inlineCode('AsyncData<A, E>'),
        ' makes the distinction the type. The idea is the pattern Elm calls RemoteData, generalized. It is a first-class value like ',
        inlineCode('Option'),
        ' or ',
        inlineCode('Result'),
        ': an ADT plus a namespace of free functions over it. You embed one Schema in your Model, and every read, transform, and transition goes through named combinators that already know the state machine. The module is the noun. It is not a data-fetching engine and not a cache. The keyed cache, the refresher, and route-driven loading stay application patterns.',
      ),
      para(
        'Throughout this page, the running example is a Notes app: a ',
        inlineCode('Note'),
        ' belongs to an optional ',
        inlineCode('Notebook'),
        ', and the Model holds several ',
        inlineCode('AsyncData'),
        ' fields for the notebook list, the cross-notebook feed, and the per-entity caches.',
      ),

      tableOfContentsEntryToHeader(sixStatesHeader),
      para(
        'The type has one axis for data presence and one for request status, and the six variants are the meaningful combinations.',
      ),
      comparisonTable(
        ['Variant', 'Payload', 'Meaning'],
        [
          [[plainCode('Idle')], ['none'], ['Nothing requested yet.']],
          [
            [plainCode('Loading')],
            ['none'],
            ['First request in flight, no prior data.'],
          ],
          [
            [plainCode('Refreshing')],
            [plainCode('{ data }')],
            ['Reloading while holding the previous good data.'],
          ],
          [
            [plainCode('Failure')],
            [plainCode('{ error }')],
            ['Request failed; showing the failure.'],
          ],
          [
            [plainCode('Stale')],
            [plainCode('{ error, data }')],
            ['Last refresh failed; still holding the previous good data.'],
          ],
          [
            [plainCode('Success')],
            [plainCode('{ data }')],
            ['Request succeeded, data present.'],
          ],
        ],
      ),
      para(
        'The public type is value-first ',
        inlineCode('AsyncData<A, E>'),
        ', matching ',
        inlineCode('Result<A, E>'),
        ' and ',
        inlineCode('Exit<A, E>'),
        '.',
      ),
      highlightedCodeBlock(
        h.div(
          [h.Class('text-sm'), h.InnerHTML(Snippet.asyncDataTypeHighlighted)],
          [],
        ),
        Snippet.asyncDataTypeRaw,
        'Copy type definition code to clipboard',
        copiedSnippets,
        'mb-8',
      ),
      para(
        'Three classifications recur across the API, and every combinator is derived from them:',
      ),
      bullets(
        h.span(
          [],
          [
            '“has data”: ',
            inlineCode('Success'),
            ', ',
            inlineCode('Refreshing'),
            ', ',
            inlineCode('Stale'),
            '.',
          ],
        ),
        h.span(
          [],
          [
            '“no data”: ',
            inlineCode('Idle'),
            ', ',
            inlineCode('Loading'),
            ', ',
            inlineCode('Failure'),
            '.',
          ],
        ),
        h.span(
          [],
          [
            '“pending” (a request in flight): ',
            inlineCode('Loading'),
            ' and ',
            inlineCode('Refreshing'),
            ' only. ',
            inlineCode('Stale'),
            ' is NOT pending; its fetch already failed.',
          ],
        ),
      ),
      infoCallout(
        'Coming from Elm',
        'The classic Elm RemoteData has four states (',
        inlineCode('NotAsked'),
        ', ',
        inlineCode('Loading'),
        ', ',
        inlineCode('Failure'),
        ', ',
        inlineCode('Success'),
        '). ',
        inlineCode('Refreshing'),
        ' and ',
        inlineCode('Stale'),
        ' are the two states this module adds, and they are the whole point of the next section.',
      ),

      tableOfContentsEntryToHeader(staleWhileRevalidateHeader),
      para(
        inlineCode('Refreshing'),
        ' and ',
        inlineCode('Stale'),
        ' are the two data-bearing states that are not fresh, and together they are the module’s differentiator. Both hold the last-good ',
        inlineCode('data'),
        ', so a view can keep rendering it, but they mean opposite things about the request.',
      ),
      para(
        inlineCode('Refreshing({ data })'),
        ' is a refetch in flight over data you already have. This is stale-while-revalidate: the list stays on screen, perhaps under a subtle spinner, while a fresh copy is on the way. Pending means a request is running, and holding data does not change that. So the combinators treat ',
        inlineCode('Refreshing'),
        ' both ways: ',
        inlineCode('getData'),
        ' hands you its data exactly as it does for ',
        inlineCode('Success'),
        ', and ',
        inlineCode('isPending'),
        ' reports true exactly as it does for ',
        inlineCode('Loading'),
        '.',
      ),
      para(
        inlineCode('Stale({ error, data })'),
        ' is a refetch that failed while data you already have is still worth showing. This is keep-stale-on-failure: the refresh errored, but rather than blanking the screen to a bare ',
        inlineCode('Failure'),
        ', the state carries both the ',
        inlineCode('error'),
        ' (so you can surface a “could not refresh” banner) and the last-good ',
        inlineCode('data'),
        ' (so the list stays up). The combinators treat it accordingly: ',
        inlineCode('getData'),
        ' hands you its data and ',
        inlineCode('getError'),
        ' hands you its error. It is the failed-refresh mirror of ',
        inlineCode('Refreshing'),
        '.',
      ),
      para(
        'Because both are type-level states, “show stale data while revalidating” and “keep stale data when the refresh fails” are things the compiler tracks for you, not conventions you re-implement per screen. A view that handles ',
        inlineCode('onRefreshing'),
        ' and ',
        inlineCode('onStale'),
        ' explicitly gets both behaviors; a view that routes them through a data handler (see ',
        inlineCode('matchData'),
        ' below) gets them for free.',
      ),

      tableOfContentsEntryToHeader(schemaBuilderHeader),
      para(
        inlineCode('AsyncData.Schema(dataSchema, errorSchema)'),
        ' returns the codec you embed in a Model, plus Schema-tightened constructors. The returned ',
        inlineCode('.schema'),
        ' is the six-state Union codec. This is the generic successor to the monomorphic factory the app used to hand-roll.',
      ),
      highlightedCodeBlock(
        h.div(
          [h.Class('text-sm'), h.InnerHTML(Snippet.asyncDataSchemaHighlighted)],
          [],
        ),
        Snippet.asyncDataSchemaRaw,
        'Copy Schema builder code to clipboard',
        copiedSnippets,
        'mb-8',
      ),
      infoCallout(
        'Error types',
        'The error Schema is simplified to ',
        inlineCode('string'),
        ' here; a real app usually gives each field a domain error Schema, for example a union of a tagged ',
        inlineCode('NotFound'),
        ' and ',
        inlineCode('string'),
        '.',
      ),
      para(
        'A single field embeds ',
        inlineCode('.schema'),
        ' directly. A keyed cache embeds it as the value Schema of an ',
        inlineCode('S.HashMap'),
        ', which is how ',
        inlineCode('noteById'),
        ' holds one independent ',
        inlineCode('AsyncData'),
        ' per ',
        inlineCode('NoteId'),
        '. The Model type of a field is ',
        inlineCode('typeof NotesAsyncData.schema.Type'),
        ', structurally equal to ',
        inlineCode('AsyncData.AsyncData<ReadonlyArray<Note>, string>'),
        '.',
      ),
      para(
        'To construct a value, use the namespace constructors (generic in ',
        inlineCode('A'),
        '/',
        inlineCode('E'),
        ') or the factory-returned ones (tightened to the Model’s ',
        inlineCode('A'),
        '/',
        inlineCode('E'),
        '). They build identical runtime values.',
      ),
      highlightedCodeBlock(
        h.div(
          [
            h.Class('text-sm'),
            h.InnerHTML(Snippet.asyncDataConstructorsHighlighted),
          ],
          [],
        ),
        Snippet.asyncDataConstructorsRaw,
        'Copy constructors code to clipboard',
        copiedSnippets,
        'mb-8',
      ),
      tableOfContentsEntryToHeader(workingWithTheValueHeader),
      para(
        'The API is a namespace of free, curried-dual functions over ',
        inlineCode('AsyncData<A, E>'),
        ' values, exactly like ',
        inlineCode('Option'),
        ', ',
        inlineCode('Result'),
        ', and ',
        inlineCode('Exit'),
        '. Every dual ships its data-last overload first, so ',
        inlineCode('pipe(notes, AsyncData.map(f))'),
        ' and ',
        inlineCode('AsyncData.map(notes, f)'),
        ' both work.',
      ),
      para(
        'The fundamental way to read a value is ',
        inlineCode('match'),
        '. It dispatches on the tag and passes the unwrapped payload to each of six required handlers. Handler keys are tag-named here because each handler covers exactly one tag. The one asymmetry is ',
        inlineCode('onStale'),
        ', which receives the whole ',
        inlineCode('{ error, data }'),
        ' object, because only ',
        inlineCode('Stale'),
        ' carries two fields.',
      ),
      highlightedCodeBlock(
        h.div(
          [h.Class('text-sm'), h.InnerHTML(Snippet.asyncDataMatchHighlighted)],
          [],
        ),
        Snippet.asyncDataMatchRaw,
        'Copy match code to clipboard',
        copiedSnippets,
        'mb-8',
      ),
      para(
        'Most views do not need six arms. ',
        inlineCode('matchData'),
        ' collapses the six states into the three channels a view usually renders: ',
        inlineCode('onData'),
        ' spans ',
        inlineCode('Success'),
        ', ',
        inlineCode('Refreshing'),
        ', AND ',
        inlineCode('Stale'),
        ', ',
        inlineCode('onFailure'),
        ' receives the ',
        inlineCode('Failure'),
        ' error, and ',
        inlineCode('onEmpty'),
        ' covers ',
        inlineCode('Idle'),
        ' and ',
        inlineCode('Loading'),
        ' together. Routing ',
        inlineCode('Stale'),
        ' through ',
        inlineCode('onData'),
        ' is the point of keeping its data. ',
        inlineCode('matchDataSplitEmpty'),
        ' is the same collapse with the two cold states split into ',
        inlineCode('onIdle'),
        ' and ',
        inlineCode('onLoading'),
        ', for views that render them differently; reach for ',
        inlineCode('match'),
        ' when the stale error or the ',
        inlineCode('Refreshing'),
        ' signal matters.',
      ),
      highlightedCodeBlock(
        h.div(
          [
            h.Class('text-sm'),
            h.InnerHTML(Snippet.asyncDataMatchDataHighlighted),
          ],
          [],
        ),
        Snippet.asyncDataMatchDataRaw,
        'Copy matchData code to clipboard',
        copiedSnippets,
        'mb-8',
      ),
      para(
        inlineCode('AsyncData.map'),
        ' transforms every data-bearing state and preserves its tag, so a pure transform does not erase the ',
        inlineCode('Refreshing'),
        ' or ',
        inlineCode('Stale'),
        ' signal. ',
        inlineCode('Stale'),
        ' maps only its ',
        inlineCode('data'),
        ' and keeps its ',
        inlineCode('error'),
        '. This is the free-function replacement for the app’s old bound ',
        inlineCode('mapData'),
        ', and it is how a mutation edits the cached list in place.',
      ),
      highlightedCodeBlock(
        h.div(
          [h.Class('text-sm'), h.InnerHTML(Snippet.asyncDataMapHighlighted)],
          [],
        ),
        Snippet.asyncDataMapRaw,
        'Copy map code to clipboard',
        copiedSnippets,
        'mb-8',
      ),
      para(
        inlineCode('getData'),
        ' returns ',
        inlineCode('Option<A>'),
        ', ',
        inlineCode('Some'),
        ' for the three data-bearing states (',
        inlineCode('Success'),
        ', ',
        inlineCode('Refreshing'),
        ', ',
        inlineCode('Stale'),
        ') and ',
        inlineCode('None'),
        ' otherwise. ',
        inlineCode('hasData'),
        ' is the boolean form, and ',
        inlineCode('getError'),
        ' / ',
        inlineCode('hasError'),
        ' are the error-channel twins, spanning ',
        inlineCode('Failure'),
        ' and ',
        inlineCode('Stale'),
        '. Reaching through a cache entry to a field is the common shape.',
      ),
      highlightedCodeBlock(
        h.div(
          [
            h.Class('text-sm'),
            h.InnerHTML(Snippet.asyncDataGetDataHighlighted),
          ],
          [],
        ),
        Snippet.asyncDataGetDataRaw,
        'Copy getData code to clipboard',
        copiedSnippets,
        'mb-8',
      ),
      infoCallout(
        'Stale is not pending',
        inlineCode('isPending'),
        ' is true for ',
        inlineCode('Loading'),
        ' and ',
        inlineCode('Refreshing'),
        ' only, NOT ',
        inlineCode('Stale'),
        '. It answers “is a request in flight”, so it drives a spinner regardless of whether data is held. ',
        inlineCode('Stale'),
        ' is not pending: in this union it does not mean merely outdated data, it is specifically the state a failed refresh leaves behind, which is why it always carries the error.',
      ),
      para(
        'The getter vocabulary is deliberate: predicates are tag-named (',
        inlineCode('isSuccess'),
        ', ',
        inlineCode('isFailure'),
        ') but getters are payload-named (',
        inlineCode('getData'),
        ', ',
        inlineCode('getError'),
        ', and their boolean twins ',
        inlineCode('hasData'),
        ', ',
        inlineCode('hasError'),
        '), because ',
        inlineCode('getData'),
        ' spans three tags and ',
        inlineCode('getError'),
        ' spans two, so a tag-named getter would be wrong.',
      ),

      tableOfContentsEntryToHeader(revalidatingHeader),
      para(
        'Two transitions drive route-entry loading, and both send ',
        inlineCode('Success'),
        ' and ',
        inlineCode('Stale'),
        ' forward into ',
        inlineCode('Refreshing'),
        ', so a revalidation always shows the last-good data while the new fetch runs.',
      ),
      para(
        inlineCode('AsyncData.revalidateOrLoad'),
        ' is the route-entry decision. It returns ',
        inlineCode('Option<AsyncData>'),
        ': cold no-data states (',
        inlineCode('Idle'),
        ', ',
        inlineCode('Failure'),
        ') start ',
        inlineCode('Loading'),
        ', already-pending states (',
        inlineCode('Loading'),
        ', ',
        inlineCode('Refreshing'),
        ') yield ',
        inlineCode('None'),
        ' so the app does not restart an in-flight fetch, and both loaded states (',
        inlineCode('Success'),
        ', ',
        inlineCode('Stale'),
        ') revalidate to ',
        inlineCode('Refreshing'),
        '. ',
        inlineCode('None'),
        ' means “no transition needed”.',
      ),
      highlightedCodeBlock(
        h.div(
          [
            h.Class('text-sm'),
            h.InnerHTML(Snippet.asyncDataRevalidateOrLoadHighlighted),
          ],
          [],
        ),
        Snippet.asyncDataRevalidateOrLoadRaw,
        'Copy revalidateOrLoad code to clipboard',
        copiedSnippets,
        'mb-8',
      ),
      para(
        inlineCode('AsyncData.revalidate'),
        ' is the narrower transition for reloading what is already loaded, typically after a mutation. It revalidates ',
        inlineCode('Success'),
        ' and ',
        inlineCode('Stale'),
        ' to ',
        inlineCode('Refreshing'),
        ' and yields ',
        inlineCode('None'),
        ' for everything else, so it never cold-starts a ',
        inlineCode('Loading'),
        ', and a cache that holds nothing is left alone.',
      ),
      highlightedCodeBlock(
        h.div(
          [
            h.Class('text-sm'),
            h.InnerHTML(Snippet.asyncDataRevalidateHighlighted),
          ],
          [],
        ),
        Snippet.asyncDataRevalidateRaw,
        'Copy revalidate code to clipboard',
        copiedSnippets,
        'mb-8',
      ),
      para(
        inlineCode('AsyncData.loadIfMissing'),
        ' is the first-visit load: the cold no-data states (',
        inlineCode('Idle'),
        ', ',
        inlineCode('Failure'),
        ') start ',
        inlineCode('Loading'),
        ', and every other state yields ',
        inlineCode('None'),
        ', so loaded data is kept without revalidation and a request in flight is not restarted. It is the load-only counterpart of ',
        inlineCode('revalidateOrLoad'),
        ', the state-machine form of “fetch on first visit, keep the cache afterwards”.',
      ),
      highlightedCodeBlock(
        h.div(
          [
            h.Class('text-sm'),
            h.InnerHTML(Snippet.asyncDataLoadIfMissingHighlighted),
          ],
          [],
        ),
        Snippet.asyncDataLoadIfMissingRaw,
        'Copy loadIfMissing code to clipboard',
        copiedSnippets,
        'mb-8',
      ),
      para(
        'These three functions are the building blocks of route-driven loading: deciding per cache, on every route change, whether to load, revalidate, or leave the state alone.',
      ),

      tableOfContentsEntryToHeader(settlingAFetchHeader),
      para(
        'When a fetch comes back, you fold the result into the field with one helper: ',
        inlineCode('settle'),
        '. It takes the previous state and a settled ',
        inlineCode('Result'),
        ' and decides the next state from both.',
      ),
      para(
        'On success, it yields ',
        inlineCode('Success'),
        '. On failure, it checks the previous state: if it ',
        inlineCode('hasData'),
        ', the failure becomes ',
        inlineCode('Stale({ error, data })'),
        ', keeping the last-good data; otherwise it becomes a bare ',
        inlineCode('Failure'),
        '. That single decision is where keep-stale pays off: it collapses a hand-written ',
        inlineCode('Succeeded*'),
        ' / ',
        inlineCode('Failed*'),
        ' handler pair into one line that keeps stale data on error.',
      ),
      para(
        'There are two valid styles for bringing a fetch back into ',
        inlineCode('update'),
        ', and neither is strictly better. The first names each outcome as its own Message, and the Command dispatches whichever happened:',
      ),
      highlightedCodeBlock(
        h.div(
          [
            h.Class('text-sm'),
            h.InnerHTML(Snippet.asyncDataSettlePairHighlighted),
          ],
          [],
        ),
        Snippet.asyncDataSettlePairRaw,
        'Copy handler pair code to clipboard',
        copiedSnippets,
        'mb-8',
      ),
      para(
        'The second folds both outcomes through one Message. The Command wraps the fetch in ',
        inlineCode('Effect.result'),
        ', so success and failure both arrive as a settled ',
        inlineCode('Result'),
        ', and dispatches a single ',
        inlineCode('Settled*'),
        ' Message carrying it. In ',
        inlineCode('update'),
        ', ',
        inlineCode('settle'),
        ' folds that ',
        inlineCode('Result'),
        ' into the previous state, and a failed refresh keeps the list instead of blanking it:',
      ),
      highlightedCodeBlock(
        h.div(
          [h.Class('text-sm'), h.InnerHTML(Snippet.asyncDataSettleHighlighted)],
          [],
        ),
        Snippet.asyncDataSettleRaw,
        'Copy settle code to clipboard',
        copiedSnippets,
        'mb-8',
      ),
      para(
        'Pick by what the outcomes mean. When success and failure drive genuinely different flows (navigate on success, open a dialog on failure), the named pair keeps each flow in its own arm. When the fetch lands in a cache field, the settled style is one arm instead of two and keeps stale data on error for free.',
      ),
      infoCallout(
        'Dropping data on purpose',
        'If you deliberately want a failed refresh to drop the previous data, write that fold as an explicit ',
        inlineCode('Result.match'),
        ' in your handler; it is not a library function, so the choice stays visible at the call site.',
      ),

      tableOfContentsEntryToHeader(combiningSeveralHeader),
      para(
        'A screen that needs several resources at once combines them with one precedence rule using ',
        inlineCode('zipWith'),
        ' (two values plus a combining function) or ',
        inlineCode('all'),
        ' (an iterable or a record). The record form of ',
        inlineCode('all'),
        ' is the multi-resource screen: it combines a record of fields into one value whose data is the struct of all the datas. The combined value is itself a ',
        inlineCode('AsyncData'),
        '.',
      ),
      highlightedCodeBlock(
        h.div(
          [h.Class('text-sm'), h.InnerHTML(Snippet.asyncDataAllHighlighted)],
          [],
        ),
        Snippet.asyncDataAllRaw,
        'Copy all code to clipboard',
        copiedSnippets,
        'mb-8',
      ),
      para(
        'The precedence, most to least dominant, is ',
        inlineCode('Failure > Loading > Idle > Stale > Refreshing > Success'),
        '. Reading it is a two-tier rule. If any input is a no-data state, the result is the highest-ranked such state with no combination, and the leftmost ',
        inlineCode('Failure'),
        '’s error wins. Otherwise every input has data, so the data is combined and the result tag is the highest-ranked data state present: any ',
        inlineCode('Stale'),
        ' makes the whole result ',
        inlineCode('Stale'),
        ', else any ',
        inlineCode('Refreshing'),
        ' makes it ',
        inlineCode('Refreshing'),
        ', else it is ',
        inlineCode('Success'),
        '. That is the payoff: the whole screen shows combined stale data while any part revalidates, and carries it forward even after a failed refresh.',
      ),
      warningCallout(
        'All-or-nothing on data',
        'The combine is all-or-nothing on data. Because the combined value needs every input’s data, a single no-data child collapses the whole result to that non-data state. ',
        inlineCode('zipWith(Idle, Success(x), f)'),
        ' discards ',
        inlineCode('x'),
        ' and yields ',
        inlineCode('Idle'),
        '. This is forced, not a bug. Combining also requires a shared error type ',
        inlineCode('E'),
        '; unify heterogeneous errors with ',
        inlineCode('mapError'),
        ' first.',
      ),
      para(
        'This section is the mental model; reach for the record form of ',
        inlineCode('all'),
        ' when one screen depends on several fields at once.',
      ),
      para(
        'A ',
        inlineCode('AsyncData'),
        ' field lives in one place: the ',
        link(coreModelRouter(), 'Model'),
        ', the single source of truth. Fetches are ',
        link(coreCommandsRouter(), 'Commands'),
        ': run the fetch through ',
        inlineCode('Effect.result'),
        ', carry the ',
        inlineCode('Result'),
        ' in the Message, and fold it in with ',
        inlineCode('settle'),
        '. ',
        link(fieldValidationRouter(), 'Field Validation'),
        ' is the sibling shipped module in the same tier, and the ',
        link(apiModuleRouter({ moduleSlug: 'async-data' }), 'API Reference'),
        ' has the generated, exhaustive catalog of every name and its per-state behavior.',
      ),
      para(
        link(comingFromTanStackQueryRouter(), 'Coming from TanStack Query'),
        ' maps the six states onto query status and cached data, and the ',
        link(
          exampleDetailRouter({ exampleSlug: 'api-cache' }),
          'api-cache example',
        ),
        ' is a full app wiring a keyed cache, a generic refresher, and route-driven loading together on this type.',
      ),
    ],
  )
}
