import { InstantCoreDatabase, i } from '@instantdb/core'

const V3ScopeEntityFields = {
  appSubjectDigest: i.string().indexed(),
  instantAppId: i.string().indexed(),
  programId: i.string().indexed(),
  programVersion: i.number(),
  protocolVersion: i.number().indexed(),
  sessionEpochId: i.string().indexed(),
  sessionId: i.string().indexed(),
  subjectId: i.string().indexed(),
}

const ProposalCommonEntityFields = {
  actorId: i.string().indexed(),
  actorSequence: i.number().indexed(),
  actorSequencePositionKey: i.string().unique().indexed(),
  causationOccurrenceId: i.string().indexed().optional(),
  clientId: i.string().indexed(),
  correlationId: i.string().indexed().optional(),
  createdAtMs: i.number().indexed(),
  envelopeJson: i.string(),
  envelopeVersion: i.number(),
  eventId: i.string().indexed(),
  eventVersion: i.number(),
  occurrenceId: i.string().indexed(),
  occurrencePositionKey: i.string().unique().indexed(),
  originDeviceId: i.string().indexed(),
  originatingProcessorId: i.string().indexed(),
  payloadJson: i.string(),
  proposalId: i.string().indexed(),
  proposalPositionKey: i.string().unique().indexed(),
  proposalKind: i.string().indexed(),
  ...V3ScopeEntityFields,
}

const ProposalVariantEntityFields = {
  admissionClaimJson: i.string().optional(),
  admissionOccurrenceId: i.string().indexed().optional(),
  causalAcceptedSequence: i.number().indexed().optional(),
  causalAudience: i.json().optional(),
  causalMessageCategory: i.string().indexed().optional(),
  causalOccurrenceId: i.string().indexed().optional(),
  causalOriginDeviceId: i.string().indexed().optional(),
  causalOriginPolicyGeneration: i.number().indexed().optional(),
  causalOriginPolicyId: i.string().indexed().optional(),
  causalOriginProofDigest: i.string().indexed().optional(),
  causalOriginatingProcessorId: i.string().indexed().optional(),
  causalPolicyGeneration: i.number().indexed().optional(),
  causalProposalId: i.string().indexed().optional(),
  effectAssignmentGeneration: i.number().indexed().optional(),
  effectCancellationGeneration: i.number().indexed().optional(),
  effectIdempotencyKey: i.string().indexed().optional(),
  effectIdempotencyPositionKey: i.string().unique().indexed().optional(),
  effectPlacementId: i.string().indexed().optional(),
  effectRequestId: i.string().indexed().optional(),
  effectRequestResultPositionKey: i.string().unique().indexed().optional(),
  executorClientCertificateJson: i.string().optional(),
  executorOriginPolicyGeneration: i.number().indexed().optional(),
  executorOriginPolicyId: i.string().indexed().optional(),
  executorProcessorCertificateJson: i.string().optional(),
  executorProcessorId: i.string().indexed().optional(),
  executorResultSignature: i.string().optional(),
  messageIdempotencyKey: i.string().indexed().optional(),
  messageIdempotencyPositionKey: i.string().unique().indexed().optional(),
  originClientCertificateJson: i.string().optional(),
  originPolicyGeneration: i.number().indexed().optional(),
  originPolicyId: i.string().indexed().optional(),
  originProcessorCertificateJson: i.string().optional(),
  originProposalSignature: i.string().optional(),
}

const CausalRoutingAndProofEntityFields = {
  causalAcceptedSequence: i.number().indexed(),
  causalAudience: i.json(),
  causalMessageCategory: i.string().indexed(),
  causalOccurrenceId: i.string().indexed(),
  causalOriginDeviceId: i.string().indexed(),
  causalOriginPolicyGeneration: i.number().indexed(),
  causalOriginPolicyId: i.string().indexed(),
  causalOriginProofDigest: i.string().indexed(),
  causalOriginatingProcessorId: i.string().indexed(),
  causalPolicyGeneration: i.number().indexed(),
  causalProposalId: i.string().indexed(),
}

/** Independent InstantDB entities for the clean protocol-v3 storage surface. */
export const InstantV3ProgramEntities = {
  foldkitV3AcceptedMessageOccurrences: i.entity({
    acceptedAtMs: i.number().indexed(),
    acceptedSequence: i.number().indexed(),
    acceptedSequencePositionKey: i.string().unique().indexed(),
    acceptingProcessorId: i.string().indexed(),
    actorId: i.string().indexed(),
    actorSequence: i.number().indexed(),
    actorSequencePositionKey: i.string().unique().indexed(),
    audience: i.json(),
    causationId: i.string().indexed().optional(),
    clientId: i.string().indexed(),
    correlationId: i.string().indexed().optional(),
    createdAtMs: i.number().indexed(),
    envelopeJson: i.string(),
    envelopeVersion: i.number(),
    eventId: i.string().indexed(),
    eventVersion: i.number(),
    messageCategory: i.string().indexed(),
    occurrenceId: i.string().indexed(),
    occurrencePositionKey: i.string().unique().indexed(),
    originDeviceId: i.string().indexed(),
    originatingProcessorId: i.string().indexed(),
    payloadJson: i.string(),
    policyGeneration: i.number().indexed(),
    positionKey: i.string().unique().indexed(),
    proposedEnvelopeJson: i.string(),
    proposalId: i.string().indexed(),
    proposalPositionKey: i.string().unique().indexed(),
    proposalKind: i.string().indexed(),
    sessionPolicy: i.json(),
    ...ProposalVariantEntityFields,
    ...V3ScopeEntityFields,
  }),
  foldkitV3EffectPlacements: i.entity({
    assignedProcessorId: i.string().indexed().optional(),
    assignmentGeneration: i.number().indexed(),
    cancellationGeneration: i.number().indexed(),
    decidedAtMs: i.number().indexed(),
    placementDecision: i.json(),
    placementId: i.string().unique().indexed(),
    placementStatus: i.string().indexed(),
    positionKey: i.string().unique().indexed(),
    requestId: i.string().indexed(),
    ...V3ScopeEntityFields,
  }),
  foldkitV3EffectRequests: i.entity({
    ...CausalRoutingAndProofEntityFields,
    effectId: i.string().indexed(),
    effectVersion: i.number(),
    idempotencyKey: i.string().indexed(),
    idempotencyPositionKey: i.string().unique().indexed(),
    minimumCapabilityVersion: i.number(),
    originatingProcessorId: i.string().indexed(),
    placement: i.json(),
    publicArguments: i.json(),
    permittedResultEvents: i.json(),
    requestId: i.string().indexed(),
    requestPositionKey: i.string().unique().indexed(),
    requestedAtMs: i.number().indexed(),
    requiredCapabilityIdJson: i.string().indexed(),
    ...V3ScopeEntityFields,
  }),
  foldkitV3MessageProposalResolutions: i.entity({
    acceptedAtMs: i.number().indexed().optional(),
    acceptedMessageOccurrenceId: i.string().unique().indexed().optional(),
    acceptedMessageOccurrencePositionKey: i
      .string()
      .unique()
      .indexed()
      .optional(),
    acceptingProcessorId: i.string().indexed().optional(),
    actorId: i.string().indexed(),
    actorSequence: i.number().indexed(),
    clientId: i.string().indexed(),
    originDeviceId: i.string().indexed(),
    originatingProcessorId: i.string().indexed(),
    proposalId: i.string().indexed(),
    proposalKind: i.string().indexed(),
    proposalTerminalPositionKey: i.string().unique().indexed(),
    rejectedAtMs: i.number().indexed().optional(),
    rejectingProcessorId: i.string().indexed().optional(),
    rejectionReason: i.string().indexed().optional(),
    resolutionState: i.string().indexed(),
    ...V3ScopeEntityFields,
  }),
  foldkitV3MessageProposals: i.entity({
    ...ProposalCommonEntityFields,
    ...ProposalVariantEntityFields,
  }),
  foldkitV3OriginEnrollmentClaims: i.entity({
    claimSignature: i.string(),
    claimedAtMs: i.number().indexed(),
    enrollmentClaimId: i.string().indexed(),
    enrollmentClaimPositionKey: i.string().unique().indexed(),
    instantAppId: i.string().indexed(),
    originDeviceId: i.string().indexed(),
    protocolVersion: i.number().indexed(),
    subjectId: i.string().indexed(),
  }),
  foldkitV3OriginPolicyDecisions: i.entity({
    decidedAtMs: i.number().indexed(),
    decidingProcessorId: i.string().indexed(),
    decision: i.json(),
    decisionId: i.string().unique().indexed(),
    decisionState: i.string().indexed(),
    enrollmentClaimId: i.string().indexed(),
    enrollmentClaimPositionKey: i.string().indexed(),
    generation: i.number().indexed(),
    instantAppId: i.string().indexed(),
    originDeviceId: i.string().indexed(),
    originPolicyId: i.string().indexed(),
    positionKey: i.string().unique().indexed(),
    previousDecisionId: i.string().indexed().optional(),
    protocolVersion: i.number().indexed(),
    subjectId: i.string().indexed(),
  }),
  foldkitV3ProgramSessions: i.entity({
    appSubjectDigest: i.string().indexed(),
    authorityProcessorId: i.string().indexed(),
    createdAtMs: i.number().indexed(),
    instantAppId: i.string().indexed(),
    lifecycleGeneration: i.number().indexed(),
    lifecyclePositionKey: i.string().unique().indexed(),
    lifecycleState: i.string().indexed(),
    originPolicyProtocolVersion: i.number().indexed(),
    previousLifecyclePositionKey: i.string().indexed().optional(),
    processorRoomId: i.string().indexed(),
    programId: i.string().indexed(),
    programVersion: i.number(),
    protocolVersion: i.number().indexed(),
    sessionEpochId: i.string().indexed(),
    sessionId: i.string().indexed(),
    sessionPolicy: i.json(),
    subjectId: i.string().indexed(),
  }),
  foldkitV3ProjectionCheckpoints: i.entity({
    checkpointId: i.string().unique().indexed(),
    createdAtMs: i.number().indexed(),
    modelDigest: i.string().indexed(),
    modelJson: i.string(),
    processorCheckpointKey: i.string().unique().indexed(),
    projectionVersion: i.number(),
    projectorProcessorId: i.string().indexed(),
    throughAcceptedSequence: i.number().indexed(),
    ...V3ScopeEntityFields,
  }),
}

/** The exact independent InstantDB schema for clean protocol-v3 records. */
export const InstantV3ProgramSchema = i.schema({
  entities: InstantV3ProgramEntities,
})

/** An InstantDB client initialized with the clean protocol-v3 Program schema. */
export type InstantV3ProgramDatabase = InstantCoreDatabase<
  typeof InstantV3ProgramSchema
>
