import { readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'

describe('Counter Expo Instant host', () => {
  it('keeps Instant out of the Expo window', () => {
    const viewSource = readFileSync('src/App.tsx', 'utf8')
    expect(viewSource).toContain('useModel(Path())')
    expect(viewSource).toContain('counterScreen')
    expect(viewSource).toContain('paintScreen')
    expect(viewSource).toContain('Starting')
    expect(viewSource).toContain('Failed')
    expect(viewSource).toContain('describeCounterSyncError')
    expect(viewSource).not.toContain('StartingWindow')
    expect(viewSource).not.toContain('signIn')
    expect(viewSource).not.toContain("useModel('/counter')")
    expect(viewSource).not.toContain('@instantdb')
    expect(viewSource).not.toContain('@foldkit/instant')
    expect(viewSource).not.toContain('instantHost')
    expect(viewSource).not.toContain('nativeDatabase')
    expect(viewSource).not.toContain('ExpoLive')
    expect(viewSource).not.toContain('store.send')
    expect(viewSource).not.toContain('store.observe')
    expect(viewSource).not.toContain('void Effect')
    expect(viewSource).toContain('accessibilityLabel="Actions"')
    expect(viewSource).toContain('onPress={trigger}')
    expect(viewSource).toContain("position: 'absolute'")
    expect(viewSource).toContain('Modal')
    expect(viewSource).toContain("visible={menu._tag === 'Open'}")
    expect(viewSource).toContain('ProgramKeyBindings')
    expect(viewSource).not.toContain('useActionMenuKeys')
    expect(viewSource).not.toContain('addEventListener')
    expect(viewSource).not.toContain('window.addEventListener')
  })

  it('installs Instant from ExpoLive at the composition root', () => {
    const hostSource = readFileSync('src/instantHost.ts', 'utf8')
    const entrySource = readFileSync('App.tsx', 'utf8')
    expect(hostSource).toContain("import './polyfill'")
    expect(hostSource.indexOf("import './polyfill'")).toBeLessThan(
      hostSource.indexOf("from './expoLive'"),
    )
    expect(hostSource).toContain('installSyncedCounterHandle')
    expect(hostSource).toContain('startLiveCounter')
    expect(hostSource).toContain('ExpoLive')
    expect(entrySource).toContain('./src/polyfill')
    expect(hostSource).not.toContain('nativeDatabase')
    expect(hostSource).not.toContain('Processor.Host.ExpoIos()')
    expect(hostSource).not.toContain('Processor.Host.ExpoAndroid()')
    expect(hostSource).not.toContain('Instant(')
    expect(hostSource).not.toContain('@foldkit/instant')
    expect(hostSource).not.toContain('@instantdb')
    expect(hostSource).not.toContain('database:')
    expect(hostSource).not.toContain('counter-instant-example')
    expect(hostSource).not.toContain('openLiveCounterWindowTape')
    expect(hostSource).not.toContain('signIn')
    expect(hostSource).not.toContain('void Effect')
    expect(entrySource).toContain('startInstantCounter')
    expect(entrySource).not.toContain('VITE_INSTANT_APP_ID')
    expect(entrySource).not.toContain('EXPO_PUBLIC_INSTANT_APP_ID')
  })

  it('puts iOS vs Android and the native database on ExpoLive', () => {
    const layerSource = readFileSync('src/expoLive.ts', 'utf8')
    expect(layerSource).toContain('export const ExpoLive')
    expect(layerSource).toContain('Platform.OS')
    expect(layerSource).toContain('Processor.Host.ExpoIos()')
    expect(layerSource).toContain('Processor.Host.ExpoAndroid()')
    expect(layerSource).toContain('Instant(')
    expect(layerSource).toContain('@instantdb/react-native')
    expect(layerSource).toContain('InstantEngine')
    expect(layerSource).toContain(
      "Symbol.for('foldkit.counter.expo.nativeDatabase')",
    )
    expect(layerSource).toContain("Symbol.for('foldkit.counter.expo.instance')")
    expect(layerSource).not.toContain('startLiveCounter')
    expect(layerSource).not.toContain('useModel')
    expect(layerSource).not.toContain('@foldkit/instant')
    expect(layerSource).not.toContain('@instantdb/admin')
  })
})
