import { Array, Option, Schema as S } from 'effect'

/** One portable Wallet route mode audited across client hosts. */
export const WalletRouteMode = S.Literals(['StateRoute', 'ReplayRoute'])
/** One portable Wallet route mode audited across client hosts. */
export type WalletRouteMode = typeof WalletRouteMode.Type

/** One client surface expected to carry the Wallet Program. */
export const WalletClientId = S.Literals([
  'ReactWeb',
  'FoldkitView',
  'RawCli',
  'EffectTerminal',
  'OpenTui',
  'ExpoWeb',
  'ExpoIos',
  'ExpoAndroid',
  'FutureServer',
])
/** One client surface expected to carry the Wallet Program. */
export type WalletClientId = typeof WalletClientId.Type

/** The implementation boundary reached by one Wallet route mode. */
export const WalletRouteSupport = S.Literals([
  'Implemented',
  'LiveBranchOnly',
  'AdapterReady',
  'ProgramOnly',
  'Planned',
])
/** The implementation boundary reached by one Wallet route mode. */
export type WalletRouteSupport = typeof WalletRouteSupport.Type

/** The strongest checked-in evidence supporting one Wallet route claim. */
export const WalletEvidenceLevel = S.Literals([
  'FocusedTest',
  'SourceInspection',
  'NoHost',
])
/** The strongest checked-in evidence supporting one Wallet route claim. */
export type WalletEvidenceLevel = typeof WalletEvidenceLevel.Type

/** Program identity that every Wallet host must consume unchanged. */
export const WalletProgramIdentity = S.Struct({
  id: S.String,
  version: S.Int,
  source: S.String,
})
/** Program identity that every Wallet host must consume unchanged. */
export type WalletProgramIdentity = typeof WalletProgramIdentity.Type

/** One exact portable Wallet route generated by the shared Program router. */
export const WalletRouteDefinition = S.Struct({
  mode: WalletRouteMode,
  title: S.String,
  routeFamily: S.String,
  portableRoute: S.String,
  representativeState: S.String,
  semantics: S.String,
})
/** One exact portable Wallet route generated by the shared Program router. */
export type WalletRouteDefinition = typeof WalletRouteDefinition.Type

/** Evidence and limitations for one client carrying one Wallet route mode. */
export const WalletRouteCapability = S.Struct({
  mode: WalletRouteMode,
  support: WalletRouteSupport,
  evidenceLevel: WalletEvidenceLevel,
  evidence: S.Array(S.String),
  limitation: S.String,
})
/** Evidence and limitations for one client carrying one Wallet route mode. */
export type WalletRouteCapability = typeof WalletRouteCapability.Type

/** Route-carrier metadata for one Wallet client surface. */
export const WalletClientDefinition = S.Struct({
  clientId: WalletClientId,
  title: S.String,
  description: S.String,
  maybeLaunchCommand: S.Option(S.String),
  maybeRouteCarrier: S.Option(S.String),
  capabilities: S.Array(WalletRouteCapability),
})
/** Route-carrier metadata for one Wallet client surface. */
export type WalletClientDefinition = typeof WalletClientDefinition.Type

/** The canonical Wallet Program identity audited by this matrix. */
export const walletProgramIdentity = WalletProgramIdentity.make({
  id: 'wallet',
  version: 2,
  source: 'examples/wallet/core/src/program.ts',
})

const representativeWalletStateRoute =
  '/wallet/state?model=%7B%22portfolio%22%3A%7B%22_tag%22%3A%22LoadedPortfolio%22%2C%22snapshot%22%3A%7B%22accounts%22%3A%5B%5D%2C%22balanceSnapshot%22%3A%7B%22observedAt%22%3A0%2C%22balances%22%3A%5B%5D%7D%2C%22receivingInstructions%22%3A%5B%5D%7D%7D%2C%22walletIntent%22%3A%7B%22_tag%22%3A%22NoWalletIntent%22%7D%2C%22addressBookEntries%22%3A%5B%5D%2C%22transaction%22%3A%7B%22_tag%22%3A%22IdleTransaction%22%7D%2C%22signature%22%3A%7B%22_tag%22%3A%22IdleSignature%22%7D%2C%22transactionObservation%22%3A%7B%22_tag%22%3A%22WaitingForAccounts%22%7D%2C%22observedTransactions%22%3A%5B%5D%7D'

const representativeWalletReplayRoute =
  '/wallet/replay?tape=%7B%22formatVersion%22%3A1%2C%22programId%22%3A%22wallet%22%2C%22programVersion%22%3A2%2C%22initialModel%22%3A%7B%22portfolio%22%3A%7B%22_tag%22%3A%22LoadedPortfolio%22%2C%22snapshot%22%3A%7B%22accounts%22%3A%5B%5D%2C%22balanceSnapshot%22%3A%7B%22observedAt%22%3A0%2C%22balances%22%3A%5B%5D%7D%2C%22receivingInstructions%22%3A%5B%5D%7D%7D%2C%22walletIntent%22%3A%7B%22_tag%22%3A%22NoWalletIntent%22%7D%2C%22addressBookEntries%22%3A%5B%5D%2C%22transaction%22%3A%7B%22_tag%22%3A%22IdleTransaction%22%7D%2C%22signature%22%3A%7B%22_tag%22%3A%22IdleSignature%22%7D%2C%22transactionObservation%22%3A%7B%22_tag%22%3A%22WaitingForAccounts%22%7D%2C%22observedTransactions%22%3A%5B%5D%7D%2C%22initialCommands%22%3A%5B%5D%2C%22transitions%22%3A%5B%7B%22sequence%22%3A1%2C%22message%22%3A%7B%22_tag%22%3A%22ImportedAddressBookEntries%22%2C%22entries%22%3A%5B%5D%7D%2C%22source%22%3A%7B%22_tag%22%3A%22Host%22%7D%2C%22isOperationSettled%22%3Atrue%2C%22commands%22%3A%5B%5D%2C%22timestamp%22%3A0%7D%5D%2C%22runtimeEvents%22%3A%5B%5D%7D&frame=1'

/** Exact representative Wallet state and replay routes generated by wallet@2. */
export const walletRoutes: ReadonlyArray<WalletRouteDefinition> = [
  WalletRouteDefinition.make({
    mode: 'StateRoute',
    title: 'State snapshot',
    routeFamily: '/wallet/state?model=<encoded Wallet Model>',
    portableRoute: representativeWalletStateRoute,
    representativeState:
      'Loaded public portfolio with zero accounts, an idle transaction, an idle signature, and no observed transactions.',
    semantics:
      'Starts from the exact public Model in the route. State routes do not restore Commands that preceded the snapshot.',
  }),
  WalletRouteDefinition.make({
    mode: 'ReplayRoute',
    title: 'Replay frame',
    routeFamily:
      '/wallet/replay?tape=<encoded wallet@2 ReplayTape>&frame=<frame>',
    portableRoute: representativeWalletReplayRoute,
    representativeState:
      'One settled ImportedAddressBookEntries transition at frame 1 over the same public Wallet Model.',
    semantics:
      'Historical Messages reconstruct the frame while historical Commands remain inert. Live continuation requires a settled branch point.',
  }),
]

const capability = (
  mode: WalletRouteMode,
  support: WalletRouteSupport,
  evidenceLevel: WalletEvidenceLevel,
  evidence: ReadonlyArray<string>,
  limitation: string,
): WalletRouteCapability =>
  WalletRouteCapability.make({
    mode,
    support,
    evidenceLevel,
    evidence,
    limitation,
  })

const implemented = (
  mode: WalletRouteMode,
  evidenceLevel: WalletEvidenceLevel,
  evidence: ReadonlyArray<string>,
  limitation: string,
): WalletRouteCapability =>
  capability(mode, 'Implemented', evidenceLevel, evidence, limitation)

/** The Wallet client surfaces and their independently audited route support. */
export const walletClients: ReadonlyArray<WalletClientDefinition> = [
  WalletClientDefinition.make({
    clientId: 'ReactWeb',
    title: 'React',
    description:
      'Shared React bindings and the standalone React web presenter.',
    maybeLaunchCommand: Option.some('pnpm --filter wallet-react-example dev'),
    maybeRouteCarrier: Option.some(
      '<react-wallet-origin><portable-wallet-route>',
    ),
    capabilities: [
      implemented(
        'StateRoute',
        'FocusedTest',
        [
          'examples/wallet/react-bindings/src/walletRoute.ts',
          'examples/wallet/react-bindings/src/wallet.test.tsx',
          'examples/wallet/react/src/main.tsx',
        ],
        'The standalone origin is a substitution point, not a deployment claim.',
      ),
      implemented(
        'ReplayRoute',
        'FocusedTest',
        [
          'examples/wallet/react-bindings/src/walletRoute.ts',
          'examples/wallet/react-bindings/src/wallet.test.tsx',
          'examples/wallet/react/src/main.tsx',
        ],
        'Inline replay opens the shared inert controller. Saved replay still requires an injected ReplayTapeStore.',
      ),
    ],
  }),
  WalletClientDefinition.make({
    clientId: 'FoldkitView',
    title: 'Foldkit',
    description: 'The canonical Foldkit view renderer over WalletProgram.',
    maybeLaunchCommand: Option.some('pnpm --filter wallet-foldkit-example dev'),
    maybeRouteCarrier: Option.some(
      '<foldkit-wallet-origin><portable-wallet-route>',
    ),
    capabilities: [
      implemented(
        'StateRoute',
        'FocusedTest',
        [
          'examples/wallet/foldkit/src/application.ts',
          'examples/wallet/foldkit/src/route.ts',
          'examples/wallet/foldkit/src/route.test.ts',
        ],
        'The standalone origin is a substitution point, not a deployment claim.',
      ),
      capability(
        'ReplayRoute',
        'ProgramOnly',
        'SourceInspection',
        [
          'examples/wallet/foldkit/src/application.ts',
          'examples/wallet/foldkit/src/route.ts',
          'examples/wallet/foldkit/src/route.test.ts',
        ],
        'The carrier rejects replay explicitly because makeFoldkitApplication cannot mount an inert ReplayController. Runtime.fromReplay would create a live branch instead.',
      ),
    ],
  }),
  WalletClientDefinition.make({
    clientId: 'RawCli',
    title: 'Raw CLI',
    description: 'A one-shot stdout host with explicit portable route input.',
    maybeLaunchCommand: Option.none(),
    maybeRouteCarrier: Option.some(
      "pnpm --filter wallet-cli-example wallet show --uri '<portable-wallet-route>' --verbose",
    ),
    capabilities: [
      implemented(
        'StateRoute',
        'SourceInspection',
        ['examples/wallet/cli/src/host.ts'],
        'State routes are one-shot CLI input, not an interactive replay session.',
      ),
      implemented(
        'ReplayRoute',
        'FocusedTest',
        [
          'examples/wallet/cli/src/host.ts',
          'examples/wallet/cli/src/host.test.ts',
        ],
        'The CLI inspects one inert replay frame and exits.',
      ),
    ],
  }),
  WalletClientDefinition.make({
    clientId: 'EffectTerminal',
    title: 'Effect Terminal',
    description: 'An interactive line-oriented Effect Terminal host.',
    maybeLaunchCommand: Option.none(),
    maybeRouteCarrier: Option.some(
      "pnpm --filter wallet-terminal-example terminal -- '<portable-wallet-route>'",
    ),
    capabilities: [
      implemented(
        'StateRoute',
        'SourceInspection',
        ['examples/wallet/terminal/src/host.ts'],
        'The route starts a live runtime directly from the decoded Model.',
      ),
      capability(
        'ReplayRoute',
        'LiveBranchOnly',
        'SourceInspection',
        ['examples/wallet/terminal/src/host.ts'],
        'The route is validated at its selected settled frame, then branched into a live runtime. It does not open inert playback.',
      ),
    ],
  }),
  WalletClientDefinition.make({
    clientId: 'OpenTui',
    title: 'OpenTUI',
    description: 'The OpenTUI React terminal reconciler.',
    maybeLaunchCommand: Option.none(),
    maybeRouteCarrier: Option.some(
      "pnpm --filter wallet-tui-example dev -- '<portable-wallet-route>'",
    ),
    capabilities: [
      implemented(
        'StateRoute',
        'SourceInspection',
        ['examples/wallet/tui/src/entry.tsx'],
        'No terminal capture is claimed for the Wallet route in this matrix.',
      ),
      implemented(
        'ReplayRoute',
        'SourceInspection',
        [
          'examples/wallet/tui/src/entry.tsx',
          'examples/wallet/tui/src/host.tsx',
        ],
        'The shared React replay controller opens the route inertly. The process test only proves clean startup and teardown.',
      ),
    ],
  }),
  WalletClientDefinition.make({
    clientId: 'ExpoWeb',
    title: 'Expo Web',
    description: 'The universal Expo Showcase running in a browser.',
    maybeLaunchCommand: Option.some(
      'pnpm --filter react-native-showcase-example web',
    ),
    maybeRouteCarrier: Option.some('<expo-web-origin><portable-wallet-route>'),
    capabilities: [
      implemented(
        'StateRoute',
        'FocusedTest',
        [
          'examples/react-native-showcase/src/App.tsx',
          'examples/react-native-showcase/src/wallet/walletProgram.test.ts',
        ],
        'The matrix has no Wallet browser capture and does not claim a deployed Expo Web origin.',
      ),
      implemented(
        'ReplayRoute',
        'SourceInspection',
        ['examples/react-native-showcase/src/App.tsx'],
        'Replay route intake is source-backed but does not yet have a focused Expo replay-route test.',
      ),
    ],
  }),
  WalletClientDefinition.make({
    clientId: 'ExpoIos',
    title: 'Expo iOS',
    description: 'The universal Expo Showcase on iOS.',
    maybeLaunchCommand: Option.some(
      'pnpm --filter react-native-showcase-example ios',
    ),
    maybeRouteCarrier: Option.some('foldkit://showcase<portable-wallet-route>'),
    capabilities: [
      implemented(
        'StateRoute',
        'SourceInspection',
        ['examples/react-native-showcase/src/App.tsx'],
        'Source wiring is present. No physical iOS behavior is claimed.',
      ),
      implemented(
        'ReplayRoute',
        'SourceInspection',
        ['examples/react-native-showcase/src/App.tsx'],
        'Source wiring opens the shared inert replay controller. No physical iOS behavior is claimed.',
      ),
    ],
  }),
  WalletClientDefinition.make({
    clientId: 'ExpoAndroid',
    title: 'Expo Android',
    description: 'The universal Expo Showcase on Android.',
    maybeLaunchCommand: Option.some(
      'pnpm --filter react-native-showcase-example android',
    ),
    maybeRouteCarrier: Option.some('foldkit://showcase<portable-wallet-route>'),
    capabilities: [
      implemented(
        'StateRoute',
        'SourceInspection',
        ['examples/react-native-showcase/src/App.tsx'],
        'Source wiring is present. No physical Android behavior is claimed.',
      ),
      implemented(
        'ReplayRoute',
        'SourceInspection',
        ['examples/react-native-showcase/src/App.tsx'],
        'Source wiring opens the shared inert replay controller. No physical Android behavior is claimed.',
      ),
    ],
  }),
  WalletClientDefinition.make({
    clientId: 'FutureServer',
    title: 'Future server',
    description: 'A future non-visual host over the portable Program runtime.',
    maybeLaunchCommand: Option.none(),
    maybeRouteCarrier: Option.none(),
    capabilities: [
      capability(
        'StateRoute',
        'Planned',
        'NoHost',
        [],
        'No server package, carrier endpoint, or execution test exists.',
      ),
      capability(
        'ReplayRoute',
        'Planned',
        'NoHost',
        [],
        'No ReplayTapeStore, server carrier endpoint, or execution test exists.',
      ),
    ],
  }),
]

/** Finds one route capability for one Wallet client. */
export const capabilityForWalletRoute = (
  client: WalletClientDefinition,
  mode: WalletRouteMode,
) =>
  Array.findFirst(client.capabilities, capability => capability.mode === mode)
