export {
  Actor,
  Affinity,
  AnyProcessor,
  AssignedFallback,
  AssignedPreferred,
  AuthenticatedActor,
  Capability,
  CapabilityId,
  CapabilityRequirement,
  Descriptor,
  Failed,
  GuestActor,
  Ignored,
  IngressProcessor,
  MessageEnvelope,
  OriginClient,
  Placement,
  PlacementDecision,
  PreviousProcessor,
  ProtocolRange,
  SpecificProcessor,
  SystemActor,
  UnavailablePolicy,
  UnavailableReason,
  Waiting,
  selectProcessor,
} from './processor.js'

export type { PlacementContext } from './processor.js'
